apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-svc
  template:
    metadata:
      labels:
        app: nginx-svc
    spec:
      containers:
        - name: nginx-svc
          image: us-docker.pkg.dev/akhilesh123/nginx/jenkins/img:$tag
          imagePullPolicy: Always
